version: "3.7"
# volumes:
# scrappr_data:
#   external: true

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - /usr/app/node_modules
      - ../:/usr/app
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    environment:
      PORT: 5000
      REDIS_URL: redis
    entrypoint:
      - /usr/app/docker/entrypoint.sh
    depends_on:
      - redis
